apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbroot
  labels:
    name: dbroot
spec:
  nfs:
    path: /home/storage/dbroot
    server: master
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbroot
  namespace: default
spec:
  selector:
    matchLabels:
      name: dbroot
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: default
spec:
  selector:
    name: db
  ports:
    - name: mysql
      targetPort: 3306
      port: 3306
  externalIPs:
  - '192.168.100.202'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      name: db
      labels: 
        name: db
    spec:
      containers:
      - name: db
        image: mydb
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: sqldb
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: dbroot
          mountPath: /dbroot
      volumes:
        - name: dbroot
          persistentVolumeClaim:
            claimName: dbroot
