apiVersion: v1
kind: PersistentVolume
metadata:
  name: wwwroot
  labels:
    name: wwwroot
spec:
  nfs:
    path: /home/storage/wwwroot
    server: master
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wwwconf
  labels:
    name: wwwconf
spec:
  nfs:
    path: /home/storage/wwwconf
    server: master
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wwwlogs
  labels:
    name: wwwlogs
spec:
  nfs:
    path: /home/storage/wwwlogs
    server: master
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wwwroot
  namespace: default
spec:
  selector:
    matchLabels:
      name: wwwroot
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wwwconf
  namespace: default
spec:
  selector:
    matchLabels:
      name: wwwconf
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wwwlogs
  namespace: default
spec:
  selector:
    matchLabels:
      name: wwwlogs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ngx-svc
  namespace: default
spec:
  selector:
    name: ngx
  ports:
    - name: http
      targetPort: 80
      port: 80
    - name: https
      targetPort: 443
      port: 443
  externalIPs:
  - '192.168.100.202'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ngx
  template:
    metadata:
      name: ngx
      labels: 
        name: ngx
    spec:
      containers:
      - name: ngx
        image: ngx
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
        - name: wwwroot
          mountPath: /wwwroot
        - name: wwwconf
          mountPath: /usr/local/openresty/nginx/conf
        - name: wwwlogs
          mountPath: /logs
      volumes:
        - name: wwwroot
          persistentVolumeClaim:
            claimName: wwwroot
        - name: wwwconf
          persistentVolumeClaim:
            claimName: wwwconf
        - name: wwwlogs
          persistentVolumeClaim:
            claimName: wwwlogs
