apiVersion: v1
kind: PersistentVolume
metadata:
  name: wwwroot
  labels:
    name: wwwroot
spec:
  nfs:
    path: /home/storage/wwwroot
    server: master
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wwwroot
  namespace: default
spec:
  selector:
    matchLabels:
      name: wwwroot
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: php7-svc
  namespace: default
spec:
  selector:
    name: php7
  ports:
    - name: php7
      targetPort: 9000
      port: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php7
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: php7
  template:
    metadata:
      name: php7
      labels: 
        name: php7
    spec:
      containers:
      - name: php7
        image: php7
        imagePullPolicy: IfNotPresent
        ports:
        - name: php
          containerPort: 9000
        volumeMounts:
        - name: wwwroot
          mountPath: /wwwroot
      volumes:
        - name: wwwroot
          persistentVolumeClaim:
            claimName: wwwroot
