#!/bin/bash
# generate iptables rules for ss

savefile=/etc/iptables/iptables.rules

echo "# Generated by SS iptables rules script v1.6.2 on $(date "+%a %b %d %T %Y")" > $savefile

cat << EOF >> $savefile
*nat
:PREROUTING ACCEPT [12504:1110483]
:INPUT ACCEPT [5815:484172]
:OUTPUT ACCEPT [3946:298006]
:POSTROUTING ACCEPT [11:602]
:SSR - [0:0]
-A PREROUTING -s 192.168.2.0/24 -j SSR
-A POSTROUTING -s 192.168.2.0/24 -j MASQUERADE
-A SSR -d 0.0.0.0/8 -j RETURN
-A SSR -d 10.0.0.0/8 -j RETURN
-A SSR -d 127.0.0.0/8 -j RETURN
-A SSR -d 169.254.0.0/16 -j RETURN
-A SSR -d 172.16.0.0/12 -j RETURN
-A SSR -d 192.168.0.0/16 -j RETURN
-A SSR -d 224.0.0.0/4 -j RETURN
-A SSR -d 240.0.0.0/4 -j RETURN
-A SSR -d ss_server_ip/32 -j RETURN
EOF

curl -s http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest | grep 'apnic|CN|ipv4' | awk -F\| '{ printf("-A SSR -d %s/%d -j RETURN\n", $4, 32-log($5)/log(2)) }' >> $savefile


cat << EOF >> $savefile
-A SSR -p icmp -j REDIRECT --to-ports 11000
-A SSR -p tcp -j REDIRECT --to-ports 11000
-A SSR -p udp -j REDIRECT --to-ports 11000
COMMIT
EOF

echo "# Completed on $(date "+%a %b %d %T %Y")" >> $savefile
echo "# Generated by SS iptables rules script v1.6.2 on $(date "+%a %b %d %T %Y")" >> $savefile

cat << EOF >> $savefile
*filter
:INPUT ACCEPT [271650:167570409]
:FORWARD ACCEPT [418494:332752246]
:OUTPUT ACCEPT [253150:151802224]
COMMIT
EOF

echo "# Completed on $(date "+%a %b %d %T %Y")" >> $savefile

systemctl reload iptables.service
